-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Eptank.Query exposing (..)

import Eptank.InputObject
import Eptank.Interface
import Eptank.Object
import Eptank.Scalar
import Eptank.ScalarCodecs
import Eptank.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias ImageRequiredArguments =
    { id : Int }


{-| get one image
-}
image :
    ImageRequiredArguments
    -> SelectionSet decodesTo Eptank.Object.ImageResult
    -> SelectionSet decodesTo RootQuery
image requiredArgs____ object____ =
    Object.selectionForCompositeField "image" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ Basics.identity


type alias ImagesRequiredArguments =
    { nimg : Int }


{-| get multiple image
-}
images :
    ImagesRequiredArguments
    -> SelectionSet decodesTo Eptank.Object.ImagesResult
    -> SelectionSet decodesTo RootQuery
images requiredArgs____ object____ =
    Object.selectionForCompositeField "images" [ Argument.required "nimg" requiredArgs____.nimg Encode.int ] object____ Basics.identity
