-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Eptank.Object.ImageResult exposing (..)

import Eptank.InputObject
import Eptank.Interface
import Eptank.Object
import Eptank.Scalar
import Eptank.ScalarCodecs
import Eptank.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


errors : SelectionSet (List String) Eptank.Object.ImageResult
errors =
    Object.selectionForField "(List String)" "errors" [] (Decode.string |> Decode.list)


image :
    SelectionSet decodesTo Eptank.Object.Image
    -> SelectionSet (Maybe decodesTo) Eptank.Object.ImageResult
image object____ =
    Object.selectionForCompositeField "image" [] object____ (Basics.identity >> Decode.nullable)


success : SelectionSet Bool Eptank.Object.ImageResult
success =
    Object.selectionForField "Bool" "success" [] Decode.bool
