-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Eptank.Object.ImagesResult exposing (..)

import Eptank.InputObject
import Eptank.Interface
import Eptank.Object
import Eptank.Scalar
import Eptank.ScalarCodecs
import Eptank.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


errors : SelectionSet (List String) Eptank.Object.ImagesResult
errors =
    Object.selectionForField "(List String)" "errors" [] (Decode.string |> Decode.list)


images :
    SelectionSet decodesTo Eptank.Object.Image
    -> SelectionSet (Maybe (List decodesTo)) Eptank.Object.ImagesResult
images object____ =
    Object.selectionForCompositeField "images" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


success : SelectionSet Bool Eptank.Object.ImagesResult
success =
    Object.selectionForField "Bool" "success" [] Decode.bool
